#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

user1 = User.create(username: "user1", email: "user1@gmail.com", password: "password", password_confirmation: "password")
user2 = User.create(username: "user2", email: "user2@gmail.com", password: "password", password_confirmation: "password")
user3 = User.create(username: "user3", email: "user3@gmail.com", password: "password", password_confirmation: "password")
user4 = User.create(username: "user4", email: "user4@gmail.com", password: "password", password_confirmation: "password")
user5 = User.create(username: "user5", email: "user5@gmail.com", password: "password", password_confirmation: "password")
user6 = User.create(username: "user6", email: "user6@gmail.com", password: "password", password_confirmation: "password")
user7 = User.create(username: "user7", email: "user7@gmail.com", password: "password", password_confirmation: "password")
user8 = User.create(username: "user8", email: "user8@gmail.com", password: "password", password_confirmation: "password")
user9 = User.create(username: "user9", email: "user9@gmail.com", password: "password", password_confirmation: "password")
user10 = User.create(username: "user10", email: "user10@gmail.com", password: "password", password_confirmation: "password")



category1 = Category.create(name:"STR", description:"Monsters, Combat, Challenges", img_url:"imgurl.com/1" )
category2 = Category.create(name:"DEX", description:"Improvization and Organization", img_url:"imgurl.com/2" )
category3 = Category.create(name:"CON", description:"World Building and Plot", img_url:"imgurl.com/3" )
category4 = Category.create(name:"INT", description:"Rules, Gold, and Balance", img_url:"imgurl.com/4" )
category5 = Category.create(name:"WIS", description:"Player Management", img_url:"imgurl.com/5" )
category6 = Category.create(name:"CHA", description:"Characters: The Good, The Bad, The Ugly", img_url:"imgurl.com/6" )



Article.create(title: "Why These Tactics?", url: "https://www.themonstersknow.com/why-these-tactics/", img_url: "https://d28hgpri8am2if.cloudfront.net/book_images/onix/cvr9781982122669/the-monsters-know-what-theyre-doing-9781982122669_hr.jpg", source: "Keith Ammann", category_id: 1)
Article.create(title: "101+ Terrain Features for Better Combats", url: "https://www.hipstersanddragons.com/terrain-features-for-fun-combats-5e/", img_url: "https://www.hipstersanddragons.com/wp-content/uploads/2016/11/cropped-DSC_0503.jpg", source: "Hipsters & Dragons", category_id: 1)
Article.create(title: "101 Traps, Puzzles, and Twists for D&D and RPG Campaigns", url: "https://hobbylark.com/tabletop-gaming/101rpgtrapsandchallenges", img_url: "https://images.saymedia-content.com/.image/c_limit%2Ccs_srgb%2Cq_auto:good%2Cw_620/MTc1Nzk2MDI4OTA4MjUxMDAx/101rpgtrapsandchallenges.webp", source: "Hobby Lark", category_id: 1)
Article.create(title: "D&D Ideas — Challenge", url: "https://nerdarchy.com/dd-ideas-challenge/", img_url: "https://nerdarchy.com/wp-content/uploads/2020/09/Nerdarchy-Logo.png", source: "Nerdarchy", category_id: 1)
Article.create(title: "A Guide to Building Encounters in D&D 5e", url: "https://arcaneeye.com/dm-tools-5e/5e-encounter-building/", img_url: "https://6lhz4vrtni-flywheel.netdna-ssl.com/wp-content/uploads/2020/05/istock-1050788020-1.svg", source: "ArcaneEye", category_id: 1)
Article.create(title: "F$&% CR, There’s a Better Way (Part 1)", url: "https://theangrygm.com/f-cr-theres-a-better-way-part-1/", img_url: "https://i0.wp.com/theangrygm.com/wp-content/uploads/2015/10/Category-Hacking-800-x-450.png?zoom=2&resize=400%2C300&ssl=1", source: "The Angry GM", category_id: 1)
Article.create(title: "For Better D&D Fights, Use This 1 Simple Trick That the Designers Won’t Tell You", url: "https://dmdavid.com/tag/for-better-dd-fights-use-this-1-simple-trick-that-the-designers-wont-tell-you/", img_url: "https://i0.wp.com/dmdavid.com/wp-content/uploads/2019/01/dragon_heist.jpg?w=717&ssl=1", source: "DM David", category_id: 1)
Article.create(title: "How to Manage Combat Like a Motherf$&%ing Dolphin", url: "https://theangrygm.com/manage-combat-like-a-dolphin/", img_url: "https://i1.wp.com/theangrygm.com/wp-content/uploads/2015/03/Category-GMing-800-x-450.png?zoom=2&resize=400%2C300&ssl=1", source: "The Angry GM", category_id: 1)
Article.create(title: "Action Oriented Monsters | Running the Game #84", url: "https://www.youtube.com/watch?v=y_zl8WWaSyI", img_url: "https://i.ytimg.com/an_webp/y_zl8WWaSyI/mqdefault_6s.webp?du=3000&sqp=CNaVo4EG&rs=AOn4CLCLxifx3AUnNI00YN1Tra-4oD0C2A", source: "Matt Colville", category_id: 1)
Article.create(title: "Roleplaying, Running the Game #83", url: "https://www.youtube.com/watch?v=7YCVHnItKuY", img_url: "https://i.ytimg.com/an_webp/7YCVHnItKuY/mqdefault_6s.webp?du=3000&sqp=CJL7ooEG&rs=AOn4CLA25S5rr86yio2o73mVTMseDVrAdg", source: "Matt Colville", category_id: 6)
Article.create(title: "Let's Kill A PC! Running the Game #68", url: "https://www.youtube.com/watch?v=xZdS8lP-Sdo", img_url: "https://i.ytimg.com/an_webp/xZdS8lP-Sdo/mqdefault_6s.webp?du=3000&sqp=CLqeo4EG&rs=AOn4CLAW8L5NW3rzOjFSjNvaITJOoFZVHg", source: "Matt Colville", category_id: 5)
Article.create(title: "Downtime, Running the Game #86", url: "https://www.youtube.com/watch?v=2fZWUPxUmYQ", img_url: "https://i.ytimg.com/an_webp/2fZWUPxUmYQ/mqdefault_6s.webp?du=3000&sqp=CLSAo4EG&rs=AOn4CLCtFOobPYgPakeXzY4GHtyXF7jETg", source: "Matt Colville", category_id: 3)
Article.create(title: "Different Kinds of Players, Running the Game #11", url: "https://www.youtube.com/watch?v=LQsJSqn71Fw", img_url: "https://i.ytimg.com/an_webp/LQsJSqn71Fw/mqdefault_6s.webp?du=3000&sqp=CMDxsoEG&rs=AOn4CLBDI9bE2Kp0Vh5-XNQxhlcG-CDmDQ", source: "Matt Colville", category_id: 3)
Article.create(title: "Catastrophic Failure, Running the Game 13/Campaign Diary 03", url: "https://www.youtube.com/watch?v=8Q8bVPpc84A", img_url: "https://i.ytimg.com/an_webp/8Q8bVPpc84A/mqdefault_6s.webp?du=3000&sqp=CMDIsoEG&rs=AOn4CLAMmgqPL0FGhsSG4P-0mBKb1dZ7uQ", source: "Matt Colville", category_id: 3)
Article.create(title: "Improvisation for New D&D Dungeon Masters", url: "https://slyflourish.com/improvisation_for_new_dms.html", img_url: "https://theiddm.files.wordpress.com/2011/06/sly-flourish-banner.png", source: "Sly Flourish", category_id: 2)
Article.create(title: "Starting Strong At Your First Dungeons & Dragons Game", url: "https://slyflourish.com/starting_strong_at_your_first_dnd_game.html", img_url: "https://theiddm.files.wordpress.com/2011/06/sly-flourish-banner.png", source: "Sly Flourish", category_id: 5)
Article.create(title: "D&D Improv: The No-Prep Guide to DMing (with Free Chapter)", url: "https://dungeonvault.com/dnd-improv-the-no-prep-guide-to-dming/", img_url: "https://dungeonvault.b-cdn.net/wp-content/uploads/2020/04/DnD-improv-no-prep.webp", source: "Dungeon Vault", category_id: 2)
Article.create(title: "The Lazy Encounter Benchmark, a Simple Measure for D&D Encounter Deadliness", url: "https://slyflourish.com/the_lazy_encounter_benchmark.html", img_url: "https://slyflourish.com/images/fantastic_lairs_cover_300w.jpg", source: "Sly Flourish", category_id: 1)
Article.create(title: "Return of the Lazy Dungeon Master", url: "https://slyflourish.com/returnofthelazydm/", img_url: "https://slyflourish.com/returnofthelazydm/lazy_dm_cover_med.jpg", source: "Sly Flourish", category_id: 5)
Article.create(title: "My Party is too Strong", url: "https://dungeonmaster.academy/articles/my-party-is-too-strong", img_url: "https://dungeonmaster.academy/assets/img/davide-lazzoni-dnd-party.jpg", source: "Dungeon Master Academy", category_id: 5)
Article.create(title: "Yes, and: Improv in Dnd", url: "https://www.reddit.com/r/DMAcademy/comments/9kocc4/yes_and_improv_in_dnd/", img_url: "https://styles.redditmedia.com/t5_3f611/styles/bannerBackgroundImage_bvxoo2ft0xo21.png", source: "r/ DM Academy", category_id: 2)
Article.create(title: "I’m Making This Up As I Go", url: "https://theangrygm.com/im-making-this-up-as-i-go/", img_url: "https://i1.wp.com/theangrygm.com/wp-content/uploads/2015/03/Category-GMing-800-x-450.png?zoom=2&resize=400%2C300&ssl=1", source: "The Angry GM", category_id: 2)
Article.create(title: "New DM, horrible at improv, ways to practice?", url: "https://www.dndbeyond.com/forums/dungeons-dragons-discussion/dungeon-masters-only/37603-new-dm-horrible-at-improv-ways-to-practice", img_url: "https://gnomestew.com/wp-content/uploads/2017/10/1eEPNQCce5HzPxTExrKWHw-ddblogo_dark.png", source: "DND Beyond", category_id: 2)



Upvote.create(user_id:1, article_id:1)
Upvote.create(user_id:1, article_id:2)
Upvote.create(user_id:1, article_id:3)
Upvote.create(user_id:1, article_id:4)
Upvote.create(user_id:1, article_id:5)
Upvote.create(user_id:1, article_id:6)
Upvote.create(user_id:1, article_id:7)
Upvote.create(user_id:1, article_id:8)
Upvote.create(user_id:1, article_id:9)
Upvote.create(user_id:1, article_id:10)
Upvote.create(user_id:1, article_id:11)
Upvote.create(user_id:1, article_id:12)
Upvote.create(user_id:1, article_id:13)
Upvote.create(user_id:1, article_id:14)
Upvote.create(user_id:1, article_id:15)
Upvote.create(user_id:1, article_id:16)
Upvote.create(user_id:1, article_id:17)
Upvote.create(user_id:1, article_id:18)
Upvote.create(user_id:1, article_id:19)
Upvote.create(user_id:1, article_id:20)
Upvote.create(user_id:1, article_id:21)
Upvote.create(user_id:1, article_id:22)
Upvote.create(user_id:1, article_id:23)
Upvote.create(user_id:2, article_id:1)
Upvote.create(user_id:2, article_id:2)
Upvote.create(user_id:2, article_id:4)
Upvote.create(user_id:2, article_id:6)
Upvote.create(user_id:2, article_id:8)
Upvote.create(user_id:2, article_id:10)
Upvote.create(user_id:2, article_id:12)
Upvote.create(user_id:2, article_id:14)
Upvote.create(user_id:2, article_id:16)
Upvote.create(user_id:2, article_id:18)
Upvote.create(user_id:2, article_id:20)
Upvote.create(user_id:2, article_id:22)
Upvote.create(user_id:3, article_id:1)
Upvote.create(user_id:3, article_id:3)
Upvote.create(user_id:3, article_id:6)
Upvote.create(user_id:3, article_id:9)
Upvote.create(user_id:3, article_id:12)
Upvote.create(user_id:3, article_id:15)
Upvote.create(user_id:3, article_id:18)
Upvote.create(user_id:3, article_id:21)
Upvote.create(user_id:4, article_id:1)
Upvote.create(user_id:4, article_id:4)
Upvote.create(user_id:4, article_id:8)
Upvote.create(user_id:4, article_id:16)
Upvote.create(user_id:4, article_id:20)
Upvote.create(user_id:5, article_id:1)
Upvote.create(user_id:5, article_id:5)
Upvote.create(user_id:5, article_id:10)
Upvote.create(user_id:5, article_id:15)
Upvote.create(user_id:5, article_id:20)
Upvote.create(user_id:6, article_id:1)
Upvote.create(user_id:6, article_id:6)
Upvote.create(user_id:6, article_id:12)
Upvote.create(user_id:6, article_id:18)
Upvote.create(user_id:7, article_id:1)
Upvote.create(user_id:7, article_id:7)
Upvote.create(user_id:7, article_id:14)
Upvote.create(user_id:7, article_id:21)
Upvote.create(user_id:8, article_id:1)
Upvote.create(user_id:8, article_id:8)
Upvote.create(user_id:8, article_id:16)
Upvote.create(user_id:9, article_id:1)
Upvote.create(user_id:9, article_id:9)
Upvote.create(user_id:9, article_id:18)
Upvote.create(user_id:10, article_id:1)
Upvote.create(user_id:10, article_id:10)
Upvote.create(user_id:10, article_id:20)